--liquibase formatted sql
--changeset rgrzegorczyk:conferences_table context:CR_conferences labels:JIRA_TASK_1
--comment Create conferences name.
--rollback  DROP TABLE conferences PURGE;
CREATE TABLE conferences 
    ( id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
    , name    VARCHAR2(255 ) 
    , description       VARCHAR2(255) 
    , country_id CHAR(2)
    , CONSTRAINT     conferences_id_pk 
        	     PRIMARY KEY (id) 
    );

--changeset jkowalski:add_dates_columns context:CR_conferences labels:JIRA_TASK_2
--comment new column
--comment Add date columns
--rollback  ALTER TABLE conferences DROP (date_from, date_to);
ALTER TABLE conferences ADD (date_from DATE, date_to DATE);    