--liquibase formatted sql
--changeset rgrzegorczyk:create_UNIVERSES_table runOnChange:false failOnError:true context:v1 labels:v1
--comment Create the UNIVERSES table
--rollback  DROP TABLE UNIVERSES PURGE;
CREATE TABLE UNIVERSES 
    ( id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
    , universe_name    VARCHAR2(40) 
    );
COMMENT ON TABLE UNIVERSES
IS 'UNIVERESES table.';

COMMENT ON COLUMN UNIVERSES.id
IS 'Primary key of universe_id table.';

COMMENT ON COLUMN UNIVERSES.universe_name
IS 'universe_id name';