ALTER SESSION SET CONTAINER=xepdb1;
SHOW CON_NAME;

CREATE USER LIQUIBASE IDENTIFIED BY HRaujc09VvZpQiGQ2fz4;

GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO LIQUIBASE;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE , UNLIMITED TABLESPACE TO LIQUIBASE;

--permission needed for generateChangelogCommand
GRANT SELECT ON SYS.DBA_RECYCLEBIN TO LIQUIBASE;